[build]
  base = "" # Thư mục gốc, để trống nếu không dùng monorepo
  publish = "build" # Thư mục build
  command = "npm run build" # Lệnh build

[dev]
  framework = "react" # Hỗ trợ React

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
